name: Compilation Windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permet de lancer la compilation manuellement

jobs:
  build:
    runs-on: windows-latest  # Lance un Windows 11 virtuel en ligne

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install pymupdf pyinstaller pillow

    - name: Créer le fichier EXE
      run: |
        pyinstaller --noconsole --onefile lecteur_pdf.py

    - name: Sauvegarder l'exécutable
      uses: actions/upload-artifact@v4
      with:
        name: lecteur-pdf-windows
        path: dist/lecteur_pdf.exe
